# NumPy Basics
## 1. NdArray - Creation
---
### * Creating and Inspecting Array

In [1]:
import numpy as np

print(2 ** 100)
print(np.int64(2) ** 100)

print("--------------------------------------")
data1 = [6, 7.5, 8, 0, 1, 2]
#data1 = [[1, 2, 3, 4], [5, 6, 7, 8]]

arr1 = np.array(data1)

print("ndarry = ", arr1)
print("Len = ", len(arr1))
print("Dim = ", arr1.ndim)
print("Shape = ", arr1.shape)
print("Type = ", arr1.dtype)

1267650600228229401496703205376
0
--------------------------------------
ndarry =  [ 6.   7.5  8.   0.   1.   2. ]
Len =  6
Dim =  1
Shape =  (6,)
Type =  float64


### * Creating Special NdArray

In [2]:
print(np.arange(15))
print(np.zeros((3, 6)))
print(np.ones(15))
print(np.eye(3))
print(np.random.rand(2, 2))

print("--------------------------------------")
print(np.arange(0, 1, 0.2))
print(np.ones_like(arr1))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]]
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
[[ 0.69768874  0.98412143]
 [ 0.47202955  0.791433  ]]
--------------------------------------
[ 0.   0.2  0.4  0.6  0.8]
[ 1.  1.  1.  1.  1.  1.]


<br> 
<br>
## 2. Array Manipulation
---
### * Reshaping and Transposing

In [3]:
int_arr1 = arr1.astype(np.int64)      # Copy
res_arr1 = int_arr1.reshape(-1, 2)    # Reference, Copy-> .copy()

print(int_arr1)
res_arr1[0, 0] = 100
print(int_arr1)
print(res_arr1)
print(arr1)

print("--------------------------------------")
print(res_arr1.ravel())               # 1-dim
print(res_arr1.T)

[6 7 8 0 1 2]
[100   7   8   0   1   2]
[[100   7]
 [  8   0]
 [  1   2]]
[ 6.   7.5  8.   0.   1.   2. ]
--------------------------------------
[100   7   8   0   1   2]
[[100   8   1]
 [  7   0   2]]


In [4]:
print(int_arr1)
int_arr1.resize((2, 3))     # Resize int_arr1 
int_arr1

[100   7   8   0   1   2]


array([[100,   7,   8],
       [  0,   1,   2]], dtype=int64)

### * Adding/Removing Elements

In [5]:
np.append(int_arr1, [9, 9, 9])

array([100,   7,   8,   0,   1,   2,   9,   9,   9], dtype=int64)

In [6]:
np.insert(int_arr1, 2, [9, 9, 9])

array([100,   7,   9,   9,   9,   8,   0,   1,   2], dtype=int64)

In [7]:
np.delete(int_arr1, (4,5))

array([100,   7,   8,   0], dtype=int64)

In [8]:
int_arr1

array([[100,   7,   8],
       [  0,   1,   2]], dtype=int64)

In [9]:
np.delete(int_arr1, 1, axis=1)

array([[100,   8],
       [  0,   2]], dtype=int64)

### * Combining and Splitting Arrays

In [10]:
np.concatenate((int_arr1, int_arr1),axis=0)

array([[100,   7,   8],
       [  0,   1,   2],
       [100,   7,   8],
       [  0,   1,   2]], dtype=int64)

In [11]:
int_arr2 = np.arange(16).reshape(4, -1)
int_arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [12]:
np.split(int_arr2, 4)    #vsplit

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [13]:
np.hsplit(int_arr2, 2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

<br>
<br>
## 3. Slicing and Indexing
---
### * Subsetting

In [14]:
int_arr3 = np.arange(6).reshape(2, -1)
int_arr3

array([[0, 1, 2],
       [3, 4, 5]])

In [15]:
int_arr3[0, 1]

1

### * Comparison

In [16]:
int_arr4 = np.arange(5)
int_arr4[np.array([True, False, False, True, True])]

array([0, 3, 4])

In [17]:
int_arr4 > 1

array([False, False,  True,  True,  True], dtype=bool)

In [18]:
int_arr1 == int_arr3

array([[False, False, False],
       [False, False, False]], dtype=bool)

In [19]:
int_arr1_cp = int_arr1.copy()
np.array_equal(int_arr1, int_arr1_cp)

True

### * Slicing

In [20]:
sli_arr = np.arange(16).reshape(4, 4)
sli_arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [21]:
sli_arr[1]

array([4, 5, 6, 7])

In [22]:
sli_arr[0:2, 1:3]

array([[1, 2],
       [5, 6]])

In [23]:
sli_arr[1:3, 2:4] = 77
sli_arr

array([[ 0,  1,  2,  3],
       [ 4,  5, 77, 77],
       [ 8,  9, 77, 77],
       [12, 13, 14, 15]])

In [24]:
sli_arr[:, 1]

array([ 1,  5,  9, 13])

In [25]:
sli_arr[:, -2]

array([ 2, 77, 77, 14])

In [26]:
sli_arr[2, ...]

array([ 8,  9, 77, 77])

In [27]:
sli_arr[:-1]

array([[ 0,  1,  2,  3],
       [ 4,  5, 77, 77],
       [ 8,  9, 77, 77]])

In [28]:
sli_arr[::-1]

array([[12, 13, 14, 15],
       [ 8,  9, 77, 77],
       [ 4,  5, 77, 77],
       [ 0,  1,  2,  3]])

### * Boolean Indexing

In [29]:
sli_arr<10

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [ True,  True, False, False],
       [False, False, False, False]], dtype=bool)

In [30]:
sli_arr[sli_arr<10]

array([0, 1, 2, 3, 4, 5, 8, 9])

In [31]:
sli_arr[(sli_arr>2) & (sli_arr<10)]

array([3, 4, 5, 8, 9])

In [32]:
sli_arr[(sli_arr<2) | (sli_arr>5)]

array([ 0,  1, 77, 77,  8,  9, 77, 77, 12, 13, 14, 15])

In [33]:
sli_arr[~(sli_arr<20)]

array([77, 77, 77, 77])

In [34]:
mat = np.random.rand(5, 5)
mat

array([[ 0.09005743,  0.76384485,  0.90468153,  0.18909139,  0.40700696],
       [ 0.32381168,  0.53993217,  0.6867699 ,  0.07629392,  0.23704312],
       [ 0.42770621,  0.15298105,  0.6499245 ,  0.50700465,  0.15731462],
       [ 0.84296586,  0.35931638,  0.40777708,  0.89721843,  0.62040399],
       [ 0.14871318,  0.31638769,  0.41909991,  0.50301399,  0.97226399]])

In [35]:
mat[np.abs(mat - mat.mean()) > 1.5*mat.std()]

array([ 0.90468153,  0.89721843,  0.97226399])

In [36]:
mat[np.abs(mat - mat.mean()) > 1.5*mat.std()] = mat.mean()

### * Fancy Indexing

In [37]:
sli_arr[[1, 0, 1, 0]]

array([[ 4,  5, 77, 77],
       [ 0,  1,  2,  3],
       [ 4,  5, 77, 77],
       [ 0,  1,  2,  3]])

In [38]:
sli_arr[[1, 0], [0, 1]]

array([4, 1])

In [39]:
sli_arr[[1, 0, 1, 0], [1, 0, 1, 0]]

array([5, 0, 5, 0])

<br>
<br>
## 4. Array Mathematics
---
### * Arithmetic Operations

In [40]:
sli_arr + sli_arr

array([[  0,   2,   4,   6],
       [  8,  10, 154, 154],
       [ 16,  18, 154, 154],
       [ 24,  26,  28,  30]])

In [41]:
sli_arr - sli_arr

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [42]:
sli_arr * sli_arr

array([[   0,    1,    4,    9],
       [  16,   25, 5929, 5929],
       [  64,   81, 5929, 5929],
       [ 144,  169,  196,  225]])

In [43]:
sli_arr @ sli_arr

array([[  56,   62,  273,  276],
       [1560, 1723, 7400, 7481],
       [1576, 1747, 7716, 7801],
       [ 344,  398, 2313, 2340]])

In [44]:
np.dot(sli_arr, sli_arr)

array([[  56,   62,  273,  276],
       [1560, 1723, 7400, 7481],
       [1576, 1747, 7716, 7801],
       [ 344,  398, 2313, 2340]])

In [45]:
sli_arr + 1

array([[ 1,  2,  3,  4],
       [ 5,  6, 78, 78],
       [ 9, 10, 78, 78],
       [13, 14, 15, 16]])

In [46]:
sli_arr * 2

array([[  0,   2,   4,   6],
       [  8,  10, 154, 154],
       [ 16,  18, 154, 154],
       [ 24,  26,  28,  30]])

In [47]:
vec = np.array([100, 100, 100, 100])
sli_arr + vec

array([[100, 101, 102, 103],
       [104, 105, 177, 177],
       [108, 109, 177, 177],
       [112, 113, 114, 115]])

In [48]:
np.exp(sli_arr)
np.sin(sli_arr)
np.log(sli_arr+1)
np.sqrt(sli_arr)

array([[ 0.        ,  1.        ,  1.41421356,  1.73205081],
       [ 2.        ,  2.23606798,  8.77496439,  8.77496439],
       [ 2.82842712,  3.        ,  8.77496439,  8.77496439],
       [ 3.46410162,  3.60555128,  3.74165739,  3.87298335]])

### * Aggregate Functions

In [49]:
sli_arr.sum()

394

In [50]:
sli_arr.min()

0

In [51]:
sli_arr.max(axis=0)

array([12, 13, 77, 77])

In [52]:
sli_arr.cumsum(axis=1)

array([[  0,   1,   3,   6],
       [  4,   9,  86, 163],
       [  8,  17,  94, 171],
       [ 12,  25,  39,  54]], dtype=int32)

In [53]:
sli_arr.mean()

24.625

In [54]:
np.median(sli_arr)

10.5

In [55]:
np.median(np.append(sli_arr, 11))

11.0

In [56]:
np.corrcoef(sli_arr)     # Correlation coefficient

array([[ 1.        ,  0.89746874,  0.8976437 ,  1.        ],
       [ 0.89746874,  1.        ,  0.99999984,  0.89746874],
       [ 0.8976437 ,  0.99999984,  1.        ,  0.8976437 ],
       [ 1.        ,  0.89746874,  0.8976437 ,  1.        ]])

In [57]:
np.std(sli_arr)          # Standard deviation

30.56524783148339

<br>
<br>
## 5. Etc
---
### * Copy

In [58]:
v = sli_arr.view()
c = sli_arr.copy()

In [59]:
np.copy(sli_arr)

array([[ 0,  1,  2,  3],
       [ 4,  5, 77, 77],
       [ 8,  9, 77, 77],
       [12, 13, 14, 15]])

In [60]:
v[1, 1] = 100
sli_arr

array([[  0,   1,   2,   3],
       [  4, 100,  77,  77],
       [  8,   9,  77,  77],
       [ 12,  13,  14,  15]])

### * Sort

In [61]:
sli_arr.sort()

In [62]:
sli_arr

array([[  0,   1,   2,   3],
       [  4,  77,  77, 100],
       [  8,   9,  77,  77],
       [ 12,  13,  14,  15]])

In [63]:
sli_arr.sort(axis=0)

In [64]:
sli_arr

array([[  0,   1,   2,   3],
       [  4,   9,  14,  15],
       [  8,  13,  77,  77],
       [ 12,  77,  77, 100]])

### * Vectorize

In [65]:
def noneg(n):
    if n < 0:
        return 0
    return n

In [66]:
noneg(7)
#noneg(sli_arr)    # Error

7

In [67]:
@np.vectorize
def noneg(n):
    if n < 0:
        return 0
    return n
noneg = np.vectorize(noneg)

In [68]:
noneg(3)

array(3)

In [69]:
noneg(3).shape

()

In [70]:
noneg(sli_arr)

array([[  0,   1,   2,   3],
       [  4,   9,  14,  15],
       [  8,  13,  77,  77],
       [ 12,  77,  77, 100]])

In [71]:
noneg(sli_arr).shape

(4, 4)

In [72]:
@np.vectorize
def noneg(n):
    if not np.isnan(n) and n < 0:
        #return 0
        return n.__class__(0)
    return n
noneg = np.vectorize(noneg)

In [73]:
noneg(np.array([-3, np.nan, 1]))

array([  0.,  nan,   1.])